# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#'
#' @param L0, L1
#' @export
compute_l <- function(L0, L1) {
    .Call('_maed_compute_l', PACKAGE = 'maed', L0, L1)
}

#' Construct P based on current discretization
#'
#' @param
#' @export
compute_p <- function(idx, R_sizes, G_size, n_stage) {
    .Call('_maed_compute_p', PACKAGE = 'maed', idx, R_sizes, G_size, n_stage)
}

#' Compute Discretization Grid Unit
#'
#' @param R_sizes, w, grid_len
#' @export
grid <- function(R_sizes, w, n_stage) {
    .Call('_maed_grid', PACKAGE = 'maed', R_sizes, w, n_stage)
}

#' element-wise floor operation on matrix
#'
#' @param
#' @export
floormat <- function(G) {
    .Call('_maed_floormat', PACKAGE = 'maed', G)
}

#' Discretization
#'
#' @param
#' @export
discretize <- function(G, R_sizes, G_size, w, n_pop, n_stage) {
    .Call('_maed_discretize', PACKAGE = 'maed', G, R_sizes, G_size, w, n_pop, n_stage)
}

#' matrix multiplication
#'
#' @param
#' @export
matmul <- function(A1, A2) {
    .Call('_maed_matmul', PACKAGE = 'maed', A1, A2)
}

