# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Average
#'
#' @param x A vector
#' @export
meanC <- function(x) {
    .Call('_maed_meanC', PACKAGE = 'maed', x)
}

